package com.azizjon.notes.backup

import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import com.azizjon.notes.data.DEFAULT_NOTEBOOK_ID
import com.azizjon.notes.data.DEFAULT_NOTEBOOK_NAME
import com.azizjon.notes.data.Note
import com.azizjon.notes.data.Notebook
import java.io.File

object SqlBackupCodec {

    fun serialize(data: BackupData): String = buildString {
        appendLine("-- Notes Android SQL backup")
        appendLine("-- This file is generated by the Android app and contains personal notes.")
        appendLine("PRAGMA foreign_keys=OFF;")
        appendLine("BEGIN TRANSACTION;")
        appendLine("DROP TABLE IF EXISTS `notes`;")
        appendLine("DROP TABLE IF EXISTS `notebooks`;")
        appendLine(
            """
            CREATE TABLE `notebooks` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `name` TEXT NOT NULL,
                `createdAt` INTEGER NOT NULL,
                `markerType` TEXT NOT NULL DEFAULT 'AUTO',
                `markerColor` INTEGER NOT NULL DEFAULT 0,
                `markerValue` TEXT NOT NULL DEFAULT '',
                `cropLeft` REAL NOT NULL DEFAULT 0,
                `cropTop` REAL NOT NULL DEFAULT 0,
                `cropSize` REAL NOT NULL DEFAULT 1
            );
            """.trimIndent(),
        )
        appendLine(
            """
            CREATE TABLE `notes` (
                `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                `title` TEXT NOT NULL,
                `content` TEXT NOT NULL,
                `notebookId` INTEGER NOT NULL DEFAULT $DEFAULT_NOTEBOOK_ID,
                `createdAt` INTEGER NOT NULL,
                `updatedAt` INTEGER NOT NULL,
                `deletedAt` INTEGER
            );
            """.trimIndent(),
        )
        appendLine("CREATE INDEX `index_notes_notebookId` ON `notes` (`notebookId`);")

        val notebooks = data.notebooks.ensureDefaultNotebook()
        notebooks.sortedBy { it.id }.forEach { notebook ->
            appendLine(
                "INSERT INTO `notebooks` (`id`,`name`,`createdAt`,`markerType`,`markerColor`,`markerValue`,`cropLeft`,`cropTop`,`cropSize`) VALUES (" +
                    listOf(
                        notebook.id.sql(),
                        notebook.name.sql(),
                        notebook.createdAt.sql(),
                        notebook.markerType.sql(),
                        notebook.markerColor.sql(),
                        notebook.markerValue.sql(),
                        notebook.cropLeft.sql(),
                        notebook.cropTop.sql(),
                        notebook.cropSize.sql(),
                    ).joinToString(",") +
                    ");",
            )
        }
        data.notes.sortedBy { it.id }.forEach { note ->
            appendLine(
                "INSERT INTO `notes` (`id`,`title`,`content`,`notebookId`,`createdAt`,`updatedAt`,`deletedAt`) VALUES (" +
                    listOf(
                        note.id.sql(),
                        note.title.sql(),
                        note.content.sql(),
                        note.notebookId.sql(),
                        note.createdAt.sql(),
                        note.updatedAt.sql(),
                        note.deletedAt?.sql() ?: "NULL",
                    ).joinToString(",") +
                    ");",
            )
        }
        appendLine("COMMIT;")
    }

    fun deserialize(context: Context, sql: String): BackupData {
        val file = File(context.cacheDir, "github-notes-restore-${System.nanoTime()}.db")
        if (file.exists()) file.delete()
        val db = SQLiteDatabase.openOrCreateDatabase(file, null)
        return try {
            executeScript(db, sql)
            readBackupData(db)
        } finally {
            db.close()
            file.delete()
        }
    }

    private fun executeScript(db: SQLiteDatabase, sql: String) {
        splitStatements(sql).forEach { statement ->
            val trimmed = statement.trim()
            if (trimmed.isNotBlank()) db.execSQL(trimmed)
        }
    }

    private fun splitStatements(sql: String): List<String> {
        val statements = mutableListOf<String>()
        val current = StringBuilder()
        var inString = false
        var i = 0
        while (i < sql.length) {
            val ch = sql[i]
            current.append(ch)
            if (ch == '\'') {
                if (inString && i + 1 < sql.length && sql[i + 1] == '\'') {
                    current.append(sql[i + 1])
                    i++
                } else {
                    inString = !inString
                }
            } else if (ch == ';' && !inString) {
                statements.add(current.toString())
                current.clear()
            }
            i++
        }
        if (current.isNotBlank()) statements.add(current.toString())
        return statements
    }

    private fun readBackupData(db: SQLiteDatabase): BackupData {
        require(tableExists(db, "notes")) { "Backup SQL does not contain notes" }
        val notebooks = if (tableExists(db, "notebooks")) {
            db.rawQuery("SELECT * FROM notebooks ORDER BY id", emptyArray()).use { cursor ->
                buildList {
                    while (cursor.moveToNext()) {
                        add(
                            Notebook(
                                id = cursor.long("id"),
                                name = cursor.string("name"),
                                createdAt = cursor.long("createdAt"),
                                markerType = cursor.string("markerType", "AUTO"),
                                markerColor = cursor.int("markerColor"),
                                markerValue = cursor.string("markerValue"),
                                cropLeft = cursor.float("cropLeft"),
                                cropTop = cursor.float("cropTop"),
                                cropSize = cursor.float("cropSize", 1f),
                            ),
                        )
                    }
                }
            }
        } else {
            emptyList()
        }.ensureDefaultNotebook()

        val noteColumns = columns(db, "notes")
        val notes = db.rawQuery("SELECT * FROM notes ORDER BY id", emptyArray()).use { cursor ->
            buildList {
                while (cursor.moveToNext()) {
                    add(
                        Note(
                            id = cursor.long("id"),
                            title = cursor.string("title"),
                            content = cursor.string("content"),
                            notebookId = if ("notebookId" in noteColumns) {
                                cursor.long("notebookId", DEFAULT_NOTEBOOK_ID)
                            } else {
                                DEFAULT_NOTEBOOK_ID
                            },
                            createdAt = cursor.long("createdAt"),
                            updatedAt = cursor.long("updatedAt"),
                            deletedAt = if ("deletedAt" in noteColumns) {
                                cursor.nullableLong("deletedAt")
                            } else {
                                null
                            },
                        ),
                    )
                }
            }
        }
        return BackupData(notebooks, notes)
    }

    private fun tableExists(db: SQLiteDatabase, table: String): Boolean =
        db.rawQuery(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ? LIMIT 1",
            arrayOf(table),
        ).use { it.moveToFirst() }

    private fun columns(db: SQLiteDatabase, table: String): Set<String> =
        db.rawQuery("PRAGMA table_info(`$table`)", emptyArray()).use { cursor ->
            buildSet {
                while (cursor.moveToNext()) add(cursor.getString(cursor.getColumnIndexOrThrow("name")))
            }
        }

    private fun List<Notebook>.ensureDefaultNotebook(): List<Notebook> =
        if (any { it.id == DEFAULT_NOTEBOOK_ID }) {
            this
        } else {
            listOf(Notebook(id = DEFAULT_NOTEBOOK_ID, name = DEFAULT_NOTEBOOK_NAME)) + this
        }

    private fun Cursor.index(name: String): Int = getColumnIndex(name)

    private fun Cursor.string(name: String, fallback: String = ""): String {
        val i = index(name)
        return if (i < 0 || isNull(i)) fallback else getString(i) ?: fallback
    }

    private fun Cursor.long(name: String, fallback: Long = 0L): Long {
        val i = index(name)
        return if (i < 0 || isNull(i)) fallback else getLong(i)
    }

    private fun Cursor.int(name: String, fallback: Int = 0): Int {
        val i = index(name)
        return if (i < 0 || isNull(i)) fallback else getInt(i)
    }

    private fun Cursor.float(name: String, fallback: Float = 0f): Float {
        val i = index(name)
        return if (i < 0 || isNull(i)) fallback else getFloat(i)
    }

    private fun Cursor.nullableLong(name: String): Long? {
        val i = index(name)
        return if (i < 0 || isNull(i)) null else getLong(i)
    }

    private fun String.sql(): String = "'${replace("'", "''")}'"
    private fun Long.sql(): String = toString()
    private fun Int.sql(): String = toString()
    private fun Float.sql(): String = toString()
}
